apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: ticketing
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-389719
  artifacts:
    - image: gcr.io/ticketing-dev-389719/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: gcr.io/ticketing-dev-389719/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
manifests:
  rawYaml:
    - ./infra/k8s/*
